### ISSUE TITLE
hash routing feature

### ISSUE THREAD

**Issue by rampall** [atomicojs/router#2]
Hi, is there a plan on the roadmap for enabling hash routing option in the Router?

**Comment by UpperCod** [comment]
Hi @rampall , Sorry for the late reply, it is supported, you just have to declare the hash and the path and that's it, example:

```ts
<RouterSwitch>
    <RouterCase path="#/user" element="my-user"/>
</RouterSwitch>
```

Remember that the use of hash is not sensitive to the pathname, so these cases will be valid for the match:

1. `/page-1/#user` 
2. `/page-2/#/user`
3. `/page-3/#user`

I invite you to join Discord https://discord.gg/7z3rNhmkNE

**Comment by rampall** [comment]
Oh, got it. Thanks!
